# Generated by Django 4.2.17 on 2024-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('resumer', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('auteur', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
